WebApplication/Controllers/AnnouncementController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class AnnouncementController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //Using ajax to accept announcement submissions
        [ValidateAntiForgeryToken]
        public JsonResult AjaxCreate(string title, string text)
        {           
            string userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            AnnouncementModels am = new AnnouncementModels();
            am.PublishTime = DateTime.Now;
            am.Text = Server.HtmlEncode(text);
            am.Title = Server.HtmlEncode(title);
            am.LecturerNo = user.LectureNo;
            am.LecturerName= user.Name;
            db.Announcements.Add(am);
            db.SaveChanges();
            return Json("Response from create");
        }

        // Retrieve all announcements via Ajax
        public JsonResult AjaxRetrieve()
        {
            var announcementModels = db.Announcements.ToList().Take(5).OrderBy(a => a.PublishTime).Reverse();
            return Json(announcementModels, JsonRequestBehavior.AllowGet);
        }


        // GET: Announcement/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnnouncementModels announcementModels = db.Announcements.Find(id);
            if (announcementModels == null)
            {
                return HttpNotFound();
            }
            return View(announcementModels);
        }

        // POST: Announcement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AnnouncementModels announcementModels = db.Announcements.Find(id);
            db.Announcements.Remove(announcementModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public JsonResult AjaxRetrieveUserName()
        {
            string userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);

            return Json(user.Name, JsonRequestBehavior.AllowGet);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class SessionController : Controller
    {
        // GET: Session
        public ActionResult Index()
        {
            return View();
        }

        //Clear the respective session via Ajax
        [ValidateAntiForgeryToken]
        public JsonResult ClearSession(string type)
        {
            Session[type] = null;
            return Json("Response from ClearSession");
        }
    }
}

WebApplication/Controllers/TestController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebApplication.Models;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class TestController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Test
        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            List<MCQModels> mCQModels = db.MCQs.ToList();
            List<MCQQuestionModel> mCQQuestionModels = new List<MCQQuestionModel>();
            foreach (var mcq in mCQModels)
            {
                if (db.Questions.Count(q => q.MCQID == mcq.ID) > 0)
                {
                    MCQQuestionModel obj = new MCQQuestionModel();

                    int questionID = db.Questions.First(q => q.MCQID == mcq.ID).ID;
                    if (db.Responses.Any(u => u.UserId == userId && u.QuestionID == questionID))
                        obj.completed = true;
                    obj.MCQID = mcq.ID;
                    obj.MCQTitle = mcq.Title;
                    obj.MCQDesc = mcq.Description;
                    obj.ReleaseDate = mcq.ReleaseDate;
                    obj.DueDate = mcq.DueDate;
                    obj.QuestionCount = db.Questions.Count(q => q.MCQID == mcq.ID);
                    mCQQuestionModels.Add(obj);
                }

            }

            return View(mCQQuestionModels);
        }

        // GET: Test/Details/5
        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MCQModels mCQModels = db.MCQs.Find(id);
            if (mCQModels == null)
            {
                return HttpNotFound();
            }
            return View(mCQModels);
        }

        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Result(int? id)
        {
            string userId = User.Identity.GetUserId();
            List<ResponseModels> responsesModels = new List<ResponseModels>();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
                responsesModels = db.Responses.Where(r => r.UserId == userId && r.MCQID == id).OrderBy(r => r.QuestionID).ToList();
            if (responsesModels == null)
            {
                return HttpNotFound();
            }
            return View(responsesModels);
        }


        // GET: Test/Start/5
        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Start(int? id)
        {
            string userId = User.Identity.GetUserId();


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionOptionViewModel qQuestionOptionViewModel = new QuestionOptionViewModel();
            qQuestionOptionViewModel.QuestionModelsList = new List<QuestionModels>();

            qQuestionOptionViewModel.MCQModels = db.MCQs.Find(id);
            if (qQuestionOptionViewModel.MCQModels == null)
            {
                return HttpNotFound();
            }
            if (db.Responses.Any(u => u.UserId == userId && u.MCQID == qQuestionOptionViewModel.MCQModels.ID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            var questions = db.Questions.Where(u => u.MCQID == id).Select(u => new
            {
                ID = u.ID
            }).ToList();

            int count = 0;

            foreach (var question in questions)
            {
                qQuestionOptionViewModel.QuestionModelsList.Add(db.Questions.Find(question.ID));
                qQuestionOptionViewModel.QuestionModelsList[count].OptionsModelsList = new List<OptionModels>();
                var options = db.Options.Where(u => u.QuestionID == question.ID);

                foreach (var option in options)
                {
                    OptionModels om = db.Options.Find(option.ID);
                    qQuestionOptionViewModel.QuestionModelsList[count].OptionsModelsList.Add(om);
                }
                count++;
            }

            return View(qQuestionOptionViewModel);
        }


        public JsonResult AjaxRetrieve()
        {
            string userId = User.Identity.GetUserId();
            int testCount = 0;
            List<MCQModels> mCQModels = db.MCQs.Where(o => o.ReleaseDate <= DateTime.Now && o.DueDate >= DateTime.Now).ToList();
            foreach (var mcq in mCQModels)
            {
                if (db.Questions.Count(q => q.MCQID == mcq.ID) > 0 && db.Responses.Count(r => r.UserId == userId && r.MCQID == mcq.ID) == 0)
                    testCount++;
            }

            return Json(testCount, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication/Views/Home/Index.cshtml
@using WebApplication.Models
@{
    ViewBag.Title = "Home Page";
}
@Html.AntiForgeryToken()
@if (!Request.IsAuthenticated)
{
    <div class="intro-header">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>BetterBoard</h1>
                    <h3>A refined version of <strike>Bad</strike>BlackBoard</h3>
                    <hr class="intro-divider">
                    <h4>Now available with external logins</h4>
                    @Html.Partial("~/Views/Account/_CustomExternalLoginsListPartial.cshtml", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
                </div>
            </div>
        </div>
    </div>
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Deadlines approaching<br>and Blackboard is showing these?</h2>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <br /><br /><br />
                    <i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
                    <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i>
                    <i class="fa fa-refresh fa-spin fa-3x fa-fw"></i>
                    <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                </div>
            </div>
        </div>
    </div>

    <div class="content-section-b">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Lost focus <br />because of bad UX?</h2>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="~/Content/img/slowboard1.jpg" alt="">
                </div>
            </div>
        </div>
    </div>

    <div class="banner">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-xs-offset-1 col-xs-offset-10">
                <h2>Switch today and say bye to the slow BlackBoard</h2>
                <br />
                @Html.Partial("~/Views/Account/_CustomExternalLoginsListPartial.cshtml", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
            </div>
        </div>
    </div>
}
else
{
    <div class="container">
        <div class="row">
            <br /><br />
        </div>
        <div class="row">
            <div class="col-lg-5 col-sm-6 col-lg-offset-2 col-md-offset-2">
                <h3>Welcome back, <span class="username"></span></h3>
                <h4><span class="weatherInfo"></span></h4>
            </div>
            @if (User.IsInRole("Student"))
                {
                <div class="col-lg-2 col-md-3 col-sm-4 col-xs-5 pull-right">
                    <div class="panel panel-info card">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="huge">Test: <span class="testCount">@Session["testCount"]</span></div>
                                </div>
                            </div>
                        </div>
                        <a href="@Url.Action("Index", "Test")">
                            <div class="panel-footer">
                                <span class="pull-left"><i class="fa fa-play" aria-hidden="true"></i> Start Test</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-lg-offset-2 col-md-offset-2">
                <div class="panel panel-info card">
                    <div class="panel-heading">
                        <h3><b><i class="fa fa-bullhorn" aria-hidden="true"></i> Announcement</b></h3>
                    </div>
                    <div class="panel-body">
                        <div class="panel-group" id="accordion">
                            <p>Loading <i class="fa fa-spinner fa-spin fa-3x fa-fw"></i></p>
                        </div>
                    </div>
                    @if (User.IsInRole("Lecturer"))
                    {
                        <form id="announcementForm">
                            <div class="panel-footer">
                                <div class="form-group">
                                    <label class="control-label col-md-2" for="Title">Title</label>
                                    <div class="col-md-10">
                                        <input class="form-control text-box single-line" id="Title" name="Title" type="text" value="" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-2" for="Text">Text</label>
                                    <div class="col-md-10">
                                        <textarea class="form-control" id="Text" name="Text" type="text" value="" required></textarea>
                                    </div>
                                </div>
                                <input type="submit" value="Publish" class="btn btn-success pull-right" />
                                <div class="clearfix"></div>
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
}
@section scripts {
    <script>
        $('.body-content').removeClass('container');
        @if (Request.IsAuthenticated)
        {<text>
        $('.body-content').addClass('container');

        $.ajax({
            type: 'GET',
            url: "@Url.Action("AjaxRetrieve", "Test")",
            success: function (res) {
                $('.testCount').text(res);
            },
            error: function (emp) {
                alert('Your Internet connection might be unstable, please refresh and try again.');
            }
        });

        $.ajax({
            type: 'GET',
            url: "@Url.Action("AjaxRetrieveUserName", "Home")",
            success: function (res) {
                $('a[href="/Manage"]').text("Hi " + res);
                $('.username').text(res);
            }
        });


        $.getJSON("http://api.openweathermap.org/data/2.5/forecast/daily?q=Swansea&mode=json&units=metric&cnt=1&APPID=f72cac1a55c68953f7b20e1a5a65ee74", function (result) {
            $('.weatherInfo').text("Swansea weather today: " + result.list[0].weather[0].description).append("<br/> Temperature: " + result.list[0].temp.day + "\xB0");
        });


        $("form").submit(function (e) {
            e.preventDefault(e);
            var data = { title: $('#Title').val(), text: $('#Text').val(), __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val() };
            $.ajax({
                type: 'POST',
                data: data,
                url: "@Url.Action("AjaxCreate", "Announcement")",
                success: function (res) {
                    $('#Title').val("");
                    $('#Text').val("");
                    getAnnouncement();
                }
            });
        });

        getAnnouncement();
        function getAnnouncement() {
            $.ajax({
                type: 'GET',
                url: "@Url.Action("AjaxRetrieve", "Announcement")",
                success: function (res) {
                    $('#accordion').html(" ");
                    for (var i = 0, l = res.length; i < l; i++) {
                        var obj = res[i];
                        var date = moment(obj.PublishTime).format("dddd, MMMM Do YYYY, h:mm:ss a");
                        $('#accordion').append('<div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse' + i + '" class="" aria-expanded="false">' + obj.Title + ' by ' + obj.LecturerName + '</a></h4></div><div id="collapse' + i + '" class="panel-collapse collapse" aria-expanded="false"><div class="panel-body">' + obj.Text + '<br><br>' + date + '</div></div></div>');
                    }
                    $('a[href=#collapse0]').trigger('click');
                }
            });
        }


        </text>
        }

        @if (Request.IsAuthenticated && !User.IsInRole("Student") && !User.IsInRole("Lecturer")) {
        <text>
        window.location.reload();
        </text>
        }

        @if (Request.IsAuthenticated && User.IsInRole("Student") && Session["loginMessage"] != null)
        {<text>
        var str = '@Session["loginMessage"]';
        setToastr();
        toastr["info"]('@Html.ActionLink("View Now", "Index", "Test", null, new { @class = "btn btn-danger btn-sm" })', str);
        ClearSession();

        function ClearSession() {
            var data = { type: 'loginMessage', __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val() };
            $.ajax({
                type: "POST",
                url: "@Url.Action("ClearSession", "Session")",
                data: data
            });
        }
        </text>}


    </script>
}