WebApplication/Controllers/ResponseController.cs
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class ResponseController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Response
        public ActionResult Index()
        {
            var responses = db.Responses.Include(r => r.ApplicationUser).Include(r => r.MCQModels).Include(r => r.OptionModels).Include(r => r.QuestionModels);
            return View(responses.ToList());
        }

        // GET: Response/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResponseModels responseModels = db.Responses.Find(id);
            if (responseModels == null)
            {
                return HttpNotFound();
            }
            return View(responseModels);
        }

        //Using ajax to accept student submissions
        [ValidateAntiForgeryToken]
        public JsonResult AjaxCreate(List<Answer> answerList)
        {
            string userId = User.Identity.GetUserId();
            foreach (Answer ans in answerList)
            {
                ResponseModels res = new ResponseModels();
                res.MCQID = ans.MCQID;
                res.OptionID = ans.OptionID;
                res.QuestionID = ans.QuestionID;
                res.UserId = userId;
                res.correct = false;
                if (!db.Responses.Any(u => u.UserId == userId && u.QuestionID == ans.QuestionID))
                {
                    if (db.Options.Where(o => o.ID == ans.OptionID).First().correct)
                        res.correct = true;
                    db.Responses.Add(res);
                    db.SaveChanges();
                }
                else
                {

                }
            }

            return Json("Response from create");
        }

        //An object for temporarily holding data from AjaxCreate() 
        public class Answer
        {
            public int MCQID { get; set; }
            public int OptionID { get; set; }
            public int QuestionID { get; set; }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Controllers/TestController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebApplication.Models;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class TestController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Test
        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            List<MCQModels> mCQModels = db.MCQs.ToList();
            List<MCQQuestionModel> mCQQuestionModels = new List<MCQQuestionModel>();
            foreach (var mcq in mCQModels)
            {
                if (db.Questions.Count(q => q.MCQID == mcq.ID) > 0)
                {
                    MCQQuestionModel obj = new MCQQuestionModel();

                    int questionID = db.Questions.First(q => q.MCQID == mcq.ID).ID;
                    if (db.Responses.Any(u => u.UserId == userId && u.QuestionID == questionID))
                        obj.completed = true;
                    obj.MCQID = mcq.ID;
                    obj.MCQTitle = mcq.Title;
                    obj.MCQDesc = mcq.Description;
                    obj.ReleaseDate = mcq.ReleaseDate;
                    obj.DueDate = mcq.DueDate;
                    obj.QuestionCount = db.Questions.Count(q => q.MCQID == mcq.ID);
                    mCQQuestionModels.Add(obj);
                }

            }

            return View(mCQQuestionModels);
        }

        // GET: Test/Details/5
        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MCQModels mCQModels = db.MCQs.Find(id);
            if (mCQModels == null)
            {
                return HttpNotFound();
            }
            return View(mCQModels);
        }

        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Result(int? id)
        {
            string userId = User.Identity.GetUserId();
            List<ResponseModels> responsesModels = new List<ResponseModels>();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
                responsesModels = db.Responses.Where(r => r.UserId == userId && r.MCQID == id).OrderBy(r => r.QuestionID).ToList();
            if (responsesModels == null)
            {
                return HttpNotFound();
            }
            return View(responsesModels);
        }


        // GET: Test/Start/5
        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Start(int? id)
        {
            string userId = User.Identity.GetUserId();


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionOptionViewModel qQuestionOptionViewModel = new QuestionOptionViewModel();
            qQuestionOptionViewModel.QuestionModelsList = new List<QuestionModels>();

            qQuestionOptionViewModel.MCQModels = db.MCQs.Find(id);
            if (qQuestionOptionViewModel.MCQModels == null)
            {
                return HttpNotFound();
            }
            if (db.Responses.Any(u => u.UserId == userId && u.MCQID == qQuestionOptionViewModel.MCQModels.ID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            var questions = db.Questions.Where(u => u.MCQID == id).Select(u => new
            {
                ID = u.ID
            }).ToList();

            int count = 0;

            foreach (var question in questions)
            {
                qQuestionOptionViewModel.QuestionModelsList.Add(db.Questions.Find(question.ID));
                qQuestionOptionViewModel.QuestionModelsList[count].OptionsModelsList = new List<OptionModels>();
                var options = db.Options.Where(u => u.QuestionID == question.ID);

                foreach (var option in options)
                {
                    OptionModels om = db.Options.Find(option.ID);
                    qQuestionOptionViewModel.QuestionModelsList[count].OptionsModelsList.Add(om);
                }
                count++;
            }

            return View(qQuestionOptionViewModel);
        }


        public JsonResult AjaxRetrieve()
        {
            string userId = User.Identity.GetUserId();
            int testCount = 0;
            List<MCQModels> mCQModels = db.MCQs.Where(o => o.ReleaseDate <= DateTime.Now && o.DueDate >= DateTime.Now).ToList();
            foreach (var mcq in mCQModels)
            {
                if (db.Questions.Count(q => q.MCQID == mcq.ID) > 0 && db.Responses.Count(r => r.UserId == userId && r.MCQID == mcq.ID) == 0)
                    testCount++;
            }

            return Json(testCount, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Views/Test/Index.cshtml
@model IEnumerable<WebApplication.ViewModels.MCQQuestionModel>


@{
    ViewBag.Title = "Test List";
}

<h1>Your Tests</h1>
@Html.AntiForgeryToken()
<div class="row" style="margin:30px 0 30px 0;">
    <div class="col-lg-12 col-md-12">
        <ul class="nav nav-custom-index nav-pills">
            <li class="current active">
                <a href="#current" data-toggle="tab" aria-expanded="true">Current</a>
            </li>
            <li class="overdue">
                <a href="#overdue" data-toggle="tab" aria-expanded="false">Overdue</a>
            </li>
            <li class="completed">
                <a href="#completed" data-toggle="tab" aria-expanded="false">Completed</a>
            </li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane fade active in" id="current">
                <br />
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    Colours indicate urgency.
                </div>
                <h3>Currently available</h3>
                @{
                    bool clearCurrent = true;
                }
                @foreach (var item in Model)
                {
                    if (item.ReleaseDate < DateTime.Now && item.DueDate > DateTime.Now && !item.completed)
                    {
                        clearCurrent = false;
                        int days = (item.DueDate - DateTime.Now).Days;
                        string bg;
                        if (days > 3 && days < 5)
                        { bg = "yellow"; }
                        else if (days < 3)
                        { bg = "red"; }
                        else
                        { bg = "info"; }
                        <div class="col-lg-6 col-md-6">
                            <div class="panel panel-@bg card">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-5">
                                            <h2><b>@Html.DisplayFor(modelItem => item.MCQTitle)</b></h2>
                                        </div>
                                        <div class="col-xs-7 text-right">
                                            <div class="huge">Questions: @Html.DisplayFor(modelItem => item.QuestionCount)</div>
                                            <div>Release: @item.ReleaseDate.ToString("yyyy/MM/dd") </div>
                                            <div>Due: @item.DueDate.ToString("yyyy/MM/dd")</div>
                                        </div>
                                    </div>
                                </div>
                                <a href="@Url.Action("Start", "Test", new { id = item.MCQID })">
                                    <div class="panel-footer">
                                        <span class="pull-left"><i class="fa fa-play" aria-hidden="true"></i> Start Test</span>
                                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                        <div class="clearfix"></div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    }
                }
                @if (clearCurrent)
                {
                    <div class="col-lg-6 col-md-6">
                        <div class="panel panel-info card">
                            <div class="panel-heading">
                                <h2><i class="fa fa-smile-o" aria-hidden="true"></i> Relax</h2>
                            </div>
                            <div class="panel-body">
                                <p>You've completed everything.</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="tab-pane fade" id="overdue">
                <br />
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    You can still view questions for overdue tests.
                </div>
                <h3>Tests Overdue</h3>
                @{
                    bool clearOverdue = true;
                }
                @foreach (var item in Model)
                {
                    if (item.DueDate < DateTime.Now && !item.completed)
                    {
                        clearOverdue = false;
                        <div class="col-lg-6 col-md-6">
                            <div class="panel panel-danger card">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-5">
                                            <h2><b>@Html.DisplayFor(modelItem => item.MCQTitle)</b></h2>
                                        </div>
                                        <div class="col-xs-7 text-right">
                                            <div class="huge">Questions: @Html.DisplayFor(modelItem => item.QuestionCount)</div>
                                            <div>Release: @item.ReleaseDate.ToString("yyyy/MM/dd") </div>
                                            <div>Due: @item.DueDate.ToString("yyyy/MM/dd")</div>
                                        </div>
                                    </div>
                                </div>
                                <a href="@Url.Action("Start", "Test", new { id = item.MCQID })">
                                    <div class="panel-footer">
                                        <span class="pull-left"><i class="fa fa-th-list" aria-hidden="true"></i> View Questions</span>
                                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                        <div class="clearfix"></div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    }
                }
                @if (clearOverdue)
                {
                    <div class="col-lg-6 col-md-6">
                        <div class="panel panel-info card">
                            <div class="panel-heading">
                                <h2><i class="fa fa-smile-o" aria-hidden="true"></i> Relax</h2>
                            </div>
                            <div class="panel-body">
                                <p>Nothing here yet.</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="tab-pane fade" id="completed">
                <br />
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    Results will be released once tests were due.
                </div>
                <h3>Tests Completed</h3>
                @{
                    bool clearCompleted = true; 
                    }
                @foreach (var item in Model)
                {
                    if (item.completed && item.DueDate < DateTime.Now)
                    {
                        clearCompleted = false;
                        <div class="col-lg-6 col-md-6">
                            <div class="panel panel-success card">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-5">
                                            <h2><b>@Html.DisplayFor(modelItem => item.MCQTitle)</b></h2>
                                        </div>
                                        <div class="col-xs-7 text-right">
                                            <div class="huge">Questions: @Html.DisplayFor(modelItem => item.QuestionCount)</div>
                                            <div>Release: @item.ReleaseDate.ToString("yyyy/MM/dd") </div>
                                            <div>Due: @item.DueDate.ToString("yyyy/MM/dd")</div>
                                        </div>
                                    </div>
                                </div>

                                <a href="@Url.Action("Result", "Test", new { id = item.MCQID })">
                                    <div class="panel-footer panel-footer-completed">
                                        <span class="pull-left"><i class="fa fa-th-list" aria-hidden="true"></i> View Result</span>
                                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                        <div class="clearfix"></div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    }                    
                }
                @if (clearCompleted)
                {
                <div class="col-lg-6 col-md-6">
                    <div class="panel panel-info card">
                        <div class="panel-heading">
                            <h2><i class="fa fa-smile-o" aria-hidden="true"></i> Relax</h2>
                        </div>
                        <div class="panel-body">
                            <p>Nothing here yet.</p>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
    </div>
@section scripts {
    <script>
    $(function() {
    $.ajax({
        type: 'GET',
        data: { __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val() },
        url: "@Url.Action("AjaxRetrieveUserName", "Home")",
        success: function (res) {
            $('a[href="/Manage"]').text("Hi " + res);
        }
    });
    });
    </script>
    }

WebApplication/Views/Test/Start.cshtml
@model WebApplication.ViewModels.QuestionOptionViewModel

@{
    ViewBag.Title = "Start";
}

<h1>@Model.MCQModels.Title</h1>
<h4>@Model.MCQModels.Description</h4>

@Html.AntiForgeryToken()

<div class="row">
    <div class="col-lg-10 col-lg-push-1">
        <div class="panel panel-primary">
            <div class="panel-heading">
                @Model.MCQModels.Title
            </div>
            @{
                int counter = 1;
                int counter2 = 1;
                int max = Model.QuestionModelsList.Count();
                string str = "active";
            }
            <div class="panel-body">
                <!-- Section for reviwing answers-->
                <div class="table-responsive" hidden>
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Question</th>
                                <th>Your answer</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var question in Model.QuestionModelsList)
                            {
                                <tr><td class="col-lg-3 col-md-3 col-sm-3">@question.Text</td><td class="col-lg-3 col-md-3 col-sm-3" id="optiontexttd-@question.ID"></td></tr>
                            }
                            <tr>
                                <td></td>
                                <td style="text-align:right;">
                                    <a href="#" class="btn btn-primary" id="reviewBack">Back</a>
                                    @if (Model.MCQModels.DueDate > DateTime.Now) {
                                    <a href="#" class="btn btn-danger" id="submitPopover" title="Confirmation" data-toggle="popover" data-placement="auto right" data-trigger="focus" data-html="true" data-content='<a class="btn btn-sm btn-danger" id="submit">Yes</a><a class="btn btn-sm btn-success pull-right" >No</a>'>Submit</a>
                                    }
                                    else
                                    {
                                        <p>Late submission isn't allowed.</p>
                                    }
                                 </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- End of Section for reviwing answers -->
                <!-- Section for answering the test-->
                <div class="answerboard">
                    <ul class="nav nav-pills nav-custom">
                        @foreach (var question in Model.QuestionModelsList)
                        {
                            if (counter2 == 1)
                            {
                                str = "active";
                            }
                            else
                            {
                                str = "";
                            }
                            <li class="@str">
                                <a href="#pills-@counter2" data-toggle="tab" aria-expanded="false">Question @counter2</a>
                            </li>
                            counter2++;
                        }
                    </ul>
                    <div class="tab-content">
                        <!-- Loop for displaying questions-->
                        @foreach (var question in Model.QuestionModelsList)
                        {
                            if (counter == 1)
                            {
                                str = "tab-pane fade in active";
                            }
                            else
                            {
                                str = "tab-pane fade";
                            }

                            <div class="@str" id="pills-@counter">
                                <h1 id="qtext-@question.ID">@question.Text</h1>
                                <hr />
                                <div class="col-lg-12">
                                    <div class="row">
                                        <!-- Loop for displaying options-->
                                        @for (int i = 0; i < Model.QuestionModelsList[counter - 1].OptionsModelsList.Count / 2; i++)
                                        {
                                            <div class="col-lg-3 col-md-3 col-sm-3">
                                                @if (i == 0)
                                                {
                                                    <h2><span id="optionA-@counter" qno="@question.ID"><strong>A </strong></span></h2>
                                                }
                                                @if (i == 1)
                                                {
                                                    <h2><span id="optionB-@counter" qno="@question.ID"><strong>B </strong></span></h2>
                                                }
                                                @if (i == 2)
                                                {
                                                    <h2><span id="optionC-@counter" qno="@question.ID"><strong>C </strong></span></h2>
                                                }
                                                @if (i == 3)
                                                {
                                                    <h2><span id="optionD-@counter" qno="@question.ID"><strong>D </strong></span></h2>
                                                }

                                                @Model.QuestionModelsList[counter - 1].OptionsModelsList[i].Text

                                                <br /><br />
                                            </div>
                                        }
                                        <!-- End of loop for displaying options-->
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-4 pull-right">
                                            <label>Answer:&nbsp;&nbsp;</label>
                                            <label class="radio-inline">
                                                <input type="radio" name="optionRadio-@counter" id="optionRadioA-@counter" qno="@question.ID" option="optionA-@counter" optiontext="@Model.QuestionModelsList[counter - 1].OptionsModelsList[0].Text" value="@Model.QuestionModelsList[counter - 1].OptionsModelsList[0].ID">A
                                            </label>
                                            <label class="radio-inline">
                                                <input type="radio" name="optionRadio-@counter" id="optionRadioB-@counter" qno="@question.ID" option="optionB-@counter" optiontext="@Model.QuestionModelsList[counter - 1].OptionsModelsList[1].Text" value="@Model.QuestionModelsList[counter - 1].OptionsModelsList[1].ID">B
                                            </label>
                                            <label class="radio-inline">
                                                <input type="radio" name="optionRadio-@counter" id="optionRadioC-@counter" qno="@question.ID" option="optionC-@counter" optiontext="@Model.QuestionModelsList[counter - 1].OptionsModelsList[2].Text" value="@Model.QuestionModelsList[counter - 1].OptionsModelsList[2].ID">C
                                            </label>
                                            <label class="radio-inline">
                                                <input type="radio" name="optionRadio-@counter" id="optionRadioD-@counter" qno="@question.ID" option="optionD-@counter" optiontext="@Model.QuestionModelsList[counter - 1].OptionsModelsList[3].Text" value="@Model.QuestionModelsList[counter - 1].OptionsModelsList[3].ID">D
                                            </label>

                                        </div>
                                    </div>

                                    <br />
                                    <hr />
                                    <div class="row">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                            @if (counter != 1)
                                            {
                                                <a class="btn btn-primary previousButton">Previous</a>
                                            }
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                            @if (counter != max)
                                            {
                                                <a class="btn btn-primary pull-right nextButton">Next</a>
                                            }
                                            else
                                            {
                                                <a href="#" class="btn btn-danger pull-right" id="submitReview">Review</a>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                            counter++;
                        }
                        <!-- End of loop for displaying questions-->
                    </div>
                </div>
                <!-- End of section for answering the test-->
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(function (){
            var answerList = [];
            var max=@max;

            $('input[type="radio"]').on("click", function () {
                $('.nav-pills > .active').addClass('answered answeredRemoved');
                var qno = $(this).attr('qno');
                var option = $(this).val();
                var str = $(this).attr('option');
                $('span[qno=' + qno + ']').removeClass("text-danger");
                $('#'+str).addClass("text-danger");
                var answer = {
                    MCQID:@Html.Raw(Json.Encode(Model.MCQModels.ID)),
                    OptionID: option,
                    QuestionID: qno
                };
                if(answerList.length==0)
                    answerList.push(answer);
                else{
                    var exist = false;
                    for (var obj in answerList) {

                        if(answerList[obj].QuestionID == qno){
                            answerList[obj].OptionID = option;
                            exist = true;
                        }
                    }
                    if(!exist)
                        answerList.push(answer);
                }
                $('#optiontexttd-'+qno).text($(this).attr('optiontext'));
            });

            $('#submitReview').click(function () {
                if(answerList.length<max){
                    toastr["error"]("Please answer all questions.", "Incomplete Test");
                }else{
                    $('.answerboard').hide();
                    $('.table-responsive').show();
                    toastr.clear();
                }
            });
            $('#reviewBack').click(function () {
                $('.table-responsive').hide();
                $('.answerboard').show();
            });

            $('.table-responsive').on("click", "#submit", function () {
                var data = { __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val(), answerList: answerList};
                /** Ajax for submitting answers **/
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("AjaxCreate", "Response")",
                    data: data,
                    success: function (res) {
                        toastr["success"]("Submission was successful. Redirect in 5 seconds.", "Complete",{timeOut: 5000});
                        setTimeout(function(){ window.location.href = "@Url.Action("Index", "Test")"; }, 5000);
                    }
                });
            });
        });
    </script>
}