WebApplication/Controllers/MCQController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebApplication.Models;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "Lecturer")]
    public class MCQController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MCQ
        public ActionResult Index()
        {
            return View(db.MCQs.ToList());
        }
        
        public ActionResult Stats(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MCQModels mCQModels = db.MCQs.Find(id);
            if (mCQModels == null)
            {
                return HttpNotFound();
            }
            
            return View(mCQModels);
        }

        //Retrieve a test via Ajax
        [ValidateAntiForgeryToken]
        public JsonResult AjaxRetrieve(int id)
        {
            List<QuestionModels> questionModelsList = db.Questions.Where(r => r.MCQID == id).ToList();
            List<Result> results = new List<Result>();

            int questionNO = 1;
            foreach (var question in questionModelsList)
            {                
                int correct = 0;
                int incorrect = 0;
                foreach (var response in db.Responses.Where(r => r.QuestionID == question.ID).ToList())
                {
                    if (response.correct)
                        correct++;
                    else
                        incorrect++;
                }

                var result = new Result();
                result.questionNo = questionNO;
                result.correct = correct;
                result.incorrect = incorrect;
                results.Add(result);

                questionNO++;
            }

            return Json(results, JsonRequestBehavior.AllowGet);
        }

        public class Result
        {
            public int questionNo { get; set; }
            public int correct { get; set; }
            public int incorrect { get; set; }
        }

        // GET: MCQ/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MCQ/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Description,ReleaseDate,DueDate")] MCQModels mCQModels)
        {
            if (ModelState.IsValid)
            {
                db.MCQs.Add(mCQModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mCQModels);
        }

        // GET: MCQ/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            QuestionOptionViewModel qQuestionOptionViewModel = new QuestionOptionViewModel();
            qQuestionOptionViewModel.QuestionModelsList = new List<QuestionModels>();

            qQuestionOptionViewModel.MCQModels = db.MCQs.Find(id);
            if (qQuestionOptionViewModel.MCQModels == null)
            {
                return HttpNotFound();
            }

            var questions = db.Questions.Where(u => u.MCQID == id).Select(u => new
            {
                ID = u.ID
            }).ToList();

            int count = 0;

            foreach (var question in questions)
            {
                qQuestionOptionViewModel.QuestionModelsList.Add(db.Questions.Find(question.ID));
                qQuestionOptionViewModel.QuestionModelsList[count].OptionsModelsList = new List<OptionModels>();
                var options = db.Options.Where(u => u.QuestionID == question.ID);

                foreach (var option in options)
                {
                    OptionModels om = db.Options.Find(option.ID);
                    qQuestionOptionViewModel.QuestionModelsList[count].OptionsModelsList.Add(om);
                }
                count++;
            }

            return View(qQuestionOptionViewModel);
        }

        // POST: MCQ/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Description,ReleaseDate,DueDate")] MCQModels mCQModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mCQModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mCQModels);
        }

        // GET: MCQ/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MCQModels mCQModels = db.MCQs.Find(id);
            if (mCQModels == null)
            {
                return HttpNotFound();
            }
            return View(mCQModels);
        }

        // POST: MCQ/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MCQModels mCQModels = db.MCQs.Find(id);
            db.MCQs.Remove(mCQModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Controllers/TestController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebApplication.Models;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class TestController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Test
        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            List<MCQModels> mCQModels = db.MCQs.ToList();
            List<MCQQuestionModel> mCQQuestionModels = new List<MCQQuestionModel>();
            foreach (var mcq in mCQModels)
            {
                if (db.Questions.Count(q => q.MCQID == mcq.ID) > 0)
                {
                    MCQQuestionModel obj = new MCQQuestionModel();

                    int questionID = db.Questions.First(q => q.MCQID == mcq.ID).ID;
                    if (db.Responses.Any(u => u.UserId == userId && u.QuestionID == questionID))
                        obj.completed = true;
                    obj.MCQID = mcq.ID;
                    obj.MCQTitle = mcq.Title;
                    obj.MCQDesc = mcq.Description;
                    obj.ReleaseDate = mcq.ReleaseDate;
                    obj.DueDate = mcq.DueDate;
                    obj.QuestionCount = db.Questions.Count(q => q.MCQID == mcq.ID);
                    mCQQuestionModels.Add(obj);
                }

            }

            return View(mCQQuestionModels);
        }

        // GET: Test/Details/5
        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MCQModels mCQModels = db.MCQs.Find(id);
            if (mCQModels == null)
            {
                return HttpNotFound();
            }
            return View(mCQModels);
        }

        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Result(int? id)
        {
            string userId = User.Identity.GetUserId();
            List<ResponseModels> responsesModels = new List<ResponseModels>();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
                responsesModels = db.Responses.Where(r => r.UserId == userId && r.MCQID == id).OrderBy(r => r.QuestionID).ToList();
            if (responsesModels == null)
            {
                return HttpNotFound();
            }
            return View(responsesModels);
        }


        // GET: Test/Start/5
        [Schaeflein.Community.MVC5AuthZPolicy.Authorize(Policy = "studentEnrolled")]
        public ActionResult Start(int? id)
        {
            string userId = User.Identity.GetUserId();


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionOptionViewModel qQuestionOptionViewModel = new QuestionOptionViewModel();
            qQuestionOptionViewModel.QuestionModelsList = new List<QuestionModels>();

            qQuestionOptionViewModel.MCQModels = db.MCQs.Find(id);
            if (qQuestionOptionViewModel.MCQModels == null)
            {
                return HttpNotFound();
            }
            if (db.Responses.Any(u => u.UserId == userId && u.MCQID == qQuestionOptionViewModel.MCQModels.ID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            var questions = db.Questions.Where(u => u.MCQID == id).Select(u => new
            {
                ID = u.ID
            }).ToList();

            int count = 0;

            foreach (var question in questions)
            {
                qQuestionOptionViewModel.QuestionModelsList.Add(db.Questions.Find(question.ID));
                qQuestionOptionViewModel.QuestionModelsList[count].OptionsModelsList = new List<OptionModels>();
                var options = db.Options.Where(u => u.QuestionID == question.ID);

                foreach (var option in options)
                {
                    OptionModels om = db.Options.Find(option.ID);
                    qQuestionOptionViewModel.QuestionModelsList[count].OptionsModelsList.Add(om);
                }
                count++;
            }

            return View(qQuestionOptionViewModel);
        }


        public JsonResult AjaxRetrieve()
        {
            string userId = User.Identity.GetUserId();
            int testCount = 0;
            List<MCQModels> mCQModels = db.MCQs.Where(o => o.ReleaseDate <= DateTime.Now && o.DueDate >= DateTime.Now).ToList();
            foreach (var mcq in mCQModels)
            {
                if (db.Questions.Count(q => q.MCQID == mcq.ID) > 0 && db.Responses.Count(r => r.UserId == userId && r.MCQID == mcq.ID) == 0)
                    testCount++;
            }

            return Json(testCount, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Views/MCQ/Create.cshtml
@model WebApplication.Models.MCQModels

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MCQ</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary pull-right" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/MCQ/Delete.cshtml
@model WebApplication.Models.MCQModels

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="row">
    <hr />
    <div class="col-lg-8 col-md-8 col-lg-offset-2 col-md-offset-2">
        <div class="panel panel-primary card">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-5">
                        <h2><b>@Html.DisplayFor(model => model.Title)</b></h2>
                    </div>
                    <div class="col-xs-7 text-right">
                        <div class="huge">@Html.DisplayFor(model => model.Description)</div>
                    </div>
                </div>
            </div>
                <div class="panel-footer" style="text-align:right">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-danger" /> |
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                    }
                </div>
        </div>
    </div>
</div>

WebApplication/Views/MCQ/Index.cshtml
@model IEnumerable<WebApplication.Models.MCQModels>

@{
    ViewBag.Title = "Index";
}

<h2>List of MCQ Tests</h2>
@Html.AntiForgeryToken()
<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>

<div class="row">
    <hr />
    @foreach (var item in Model)
    {
        <div class="col-lg-6 col-md-6">
            <div class="panel panel-info card">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-5">
                            <h2><b>@Html.DisplayFor(modelItem => item.Title)</b></h2>
                        </div>
                        <div class="col-xs-7 text-right">
                            <div>@Html.DisplayFor(modelItem => item.Description)</div>
                            <div>Release: @item.ReleaseDate.ToString("yyyy/MM/dd") </div>
                            <div>Due: @item.DueDate.ToString("yyyy/MM/dd")</div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer" style="text-align:right">
                    <div class="form-actions no-color">
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-primary" })

                        @Html.ActionLink("View Stats", "Stats", new { id = item.ID }, new { @class = "btn btn-info" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@section scripts {
    <script>
    @if (Request.IsAuthenticated)
       {<text>
        $('.body-content').addClass('container');

        $.ajax({
            type: 'GET',
            url: "@Url.Action("AjaxRetrieve", "Test")",
            success: function (res) {
                $('.testCount').text(res);
            },
            error: function (emp) {
                alert('Your Internet connection might be unstable, please refresh and try again.');
            }
        });

        $.ajax({
            type: 'GET',
            url: "@Url.Action("AjaxRetrieveUserName", "Home")",
            success: function (res) {
                $('a[href="/Manage"]').text("Hi " + res);
            }
        });

        </text>
        }
    </script>
}

WebApplication/Views/MCQ/Stats.cshtml
@model WebApplication.Models.MCQModels

@{
    ViewBag.Title = "Test Stats";
}

<h2>Results for @Model.Title</h2>
@Html.AntiForgeryToken()

<div class="row">
    <div class="col-lg-10 col-lg-push-1">
        <canvas id="bar-chart" width="600" height="350"></canvas>
    </div>
</div>
<p>
@Html.ActionLink("Back to Dashboard", "Index", null, new { @class = "btn btn-success pull-right" })
    <br />
</p>
@section Scripts {
    <script>
        var questionNo=[];
        var correct=[];
        var incorrect=[];
        var max = 0;

        $.ajax({
            type: 'POST',
            url: "@Url.Action("AjaxRetrieve", "MCQ")",
            data: {id:@Model.ID,__RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()},
            success: function (res) {
                for(var i=0;i<res.length;i++){
                    questionNo.push("Question "+res[i].questionNo);
                    correct.push(res[i].correct);
                    incorrect.push(res[i].incorrect);

                    if(res[i].correct>max)
                        max=res[i].correct;
                    if(res[i].incorrect>max)
                        max=res[i].incorrect;
                }


                var bar_ctx = $('#bar-chart');
                var bar_chart = new Chart(bar_ctx, {
                    type: 'bar',
                    data: {
                        labels: questionNo,
                        datasets: [
                        {
                            label: 'Correct',
                            data: correct,
                            backgroundColor: "#5cb85c",
                            hoverBackgroundColor: "#5cb85c",
                            hoverBorderWidth: 2,
                            hoverBorderColor: 'lightgrey'
                        },
                        {
                            label: 'Incorrect',
                            data: incorrect,
                            backgroundColor: "#d9534f",
                            hoverBackgroundColor: "#d9534f",
                            hoverBorderWidth: 2,
                            hoverBorderColor: 'lightgrey'
                        },
                        ]
                    },
                    options: {
                        animation: {
                            duration: 10,
                        },
                        tooltips: {
                            mode: 'label',
                            callbacks: {
                                label: function (tooltipItem, data) {
                                    return data.datasets[tooltipItem.datasetIndex].label + ": " + tooltipItem.yLabel;
                                }
                            }
                        },
                        scales: {
                            xAxes: [{
                                stacked: true,
                                gridLines: { display: false },
                            }],
                            yAxes: [{
                                stacked: true,
                                ticks: {
                                    scaleSteps: max,
                                    stepSize: 1,
                                    scaleStepWidth: 1,
                                    scaleStartValue: 0,
                                },
                                scaleLabel: {
                                    display: true,
                                    labelString: 'Number of responses'
                                },
                            }],
                        },
                        legend: { display: true }
                    }
                });
            },
            error: function (emp) {
                alert('Your Internet connection might be unstable, please try again.');
            }
        });
    </script>
}